---
- name: Ensure dependency is installed (Ubuntu).
  apt: name=apt-transport-https state=present

- name: Install latest version of "kibana" and "install-recommends"
  apt:
    name: kibana
    state: latest
    install_recommends: yes
