---
- name: Ensure dependency is installed (Ubuntu).
  apt: name=apt-transport-https state=present

- name: Install latest version of "kibana" and "install-recommends"
  apt:
    name: kibana
    state: latest
    install_recommends: yes

- name: Configure Kibana.
  template:
    src: kibana.yml.base
    dest: /etc/kibana/kibana.yml
  notify: restart kibana

- name: Deamon Kibana Search
  command: "sudo update-rc.d kibana defaults 95 10"